# First value is the value that it is serialized as
# Second value is the path to load it from
SERIALIZABLE_MAPPING = {
    ("langchain_core", "agents", "AgentActionMessageLog"): (
        "langchain_core",
        "agents",
        "AgentActionMessageLog",
    ),
    ("langchain_core", "messages", "system", "SystemMessage"): (
        "langchain_core",
        "messages",
        "system",
        "SystemMessage",
    ),
    ("langchain_core", "runnables", "RunnablePassthrough"): (
        "langchain_core",
        "runnables",
        "RunnablePassthrough",
    ),
    ("langchain_core", "outputs", "chat_generation", "ChatGeneration"): (
        "langchain_core",
        "outputs",
        "chat_generation",
        "ChatGeneration",
    ),
    ("langchain_core", "messages", "tool", "ToolMessage"): (
        "langchain_core",
        "messages",
        "tool",
        "ToolMessage",
    ),
    ("langchain_core", "outputs", "generation", "Generation"): (
        "langchain_core",
        "outputs",
        "generation",
        "Generation",
    ),
    ("langchain_core", "runnables", "RunnableParallel"): (
        "langchain_core",
        "runnables",
        "RunnableParallel",
    ),
    ("langchain_core", "messages", "function", "FunctionMessageChunk"): (
        "langchain_core",
        "messages",
        "function",
        "FunctionMessageChunk",
    ),
    ("langchain_core", "prompts", "chat", "BaseChatPromptTemplate"): (
        "langchain_core",
        "prompts",
        "chat",
        "BaseChatPromptTemplate",
    ),
    ("langchain_core", "runnables", "RunnableSequence"): (
        "langchain_core",
        "runnables",
        "RunnableSequence",
    ),
    ("langchain_core", "prompt_values", "StringPromptValue"): (
        "langchain_core",
        "prompt_values",
        "StringPromptValue",
    ),
    ("langchain_core", "prompts", "chat", "ChatMessagePromptTemplate"): (
        "langchain_core",
        "prompts",
        "chat",
        "ChatMessagePromptTemplate",
    ),
    ("langchain_core", "prompts", "chat", "HumanMessagePromptTemplate"): (
        "langchain_core",
        "prompts",
        "chat",
        "HumanMessagePromptTemplate",
    ),
    ("langchain_core", "prompts", "chat", "BaseMessagePromptTemplate"): (
        "langchain_core",
        "prompts",
        "chat",
        "BaseMessagePromptTemplate",
    ),
    ("langchain_core", "documents", "base", "Document"): (
        "langchain_core",
        "documents",
        "base",
        "Document",
    ),
    ("langchain_core", "runnables", "RunnableBindingBase"): (
        "langchain_core",
        "runnables",
        "RunnableBindingBase",
    ),
    ("langchain_core", "prompts", "prompt", "PromptTemplate"): (
        "langchain_core",
        "prompts",
        "prompt",
        "PromptTemplate",
    ),
    ("langchain_core", "prompts", "chat", "ChatPromptTemplate"): (
        "langchain_core",
        "prompts",
        "chat",
        "ChatPromptTemplate",
    ),
    ("langchain_core", "runnables", "DynamicRunnable"): (
        "langchain_core",
        "runnables",
        "DynamicRunnable",
    ),
    ("langchain_core", "messages", "function", "FunctionMessage"): (
        "langchain_core",
        "messages",
        "function",
        "FunctionMessage",
    ),
    ("langchain_core", "messages", "ai", "AIMessage"): (
        "langchain_core",
        "messages",
        "ai",
        "AIMessage",
    ),
    ("langchain_core", "prompt_values", "ChatPromptValue"): (
        "langchain_core",
        "prompt_values",
        "ChatPromptValue",
    ),
    ("langchain_core", "messages", "ai", "AIMessageChunk"): (
        "langchain_core",
        "messages",
        "ai",
        "AIMessageChunk",
    ),
    ("langchain_core", "runnables", "RunnableEachBase"): (
        "langchain_core",
        "runnables",
        "RunnableEachBase",
    ),
    ("langchain_core", "messages", "chat", "ChatMessage"): (
        "langchain_core",
        "messages",
        "chat",
        "ChatMessage",
    ),
    ("langchain_core", "messages", "human", "HumanMessageChunk"): (
        "langchain_core",
        "messages",
        "human",
        "HumanMessageChunk",
    ),
    ("langchain_core", "prompts", "pipeline", "PipelinePromptTemplate"): (
        "langchain_core",
        "prompts",
        "pipeline",
        "PipelinePromptTemplate",
    ),
    ("langchain_core", "runnables", "RouterRunnable"): (
        "langchain_core",
        "runnables",
        "RouterRunnable",
    ),
    ("langchain_core", "messages", "base", "BaseMessageChunk"): (
        "langchain_core",
        "messages",
        "base",
        "BaseMessageChunk",
    ),
    ("langchain_core", "prompt_values", "ChatPromptValueConcrete"): (
        "langchain_core",
        "prompt_values",
        "ChatPromptValueConcrete",
    ),
    ("langchain_core", "agents", "AgentAction"): (
        "langchain_core",
        "agents",
        "AgentAction",
    ),
    ("langchain_core", "prompts", "chat", "MessagesPlaceholder"): (
        "langchain_core",
        "prompts",
        "chat",
        "MessagesPlaceholder",
    ),
    ("langchain_core", "outputs", "chat_generation", "ChatGenerationChunk"): (
        "langchain_core",
        "outputs",
        "chat_generation",
        "ChatGenerationChunk",
    ),
    ("langchain_core", "prompts", "chat", "AIMessagePromptTemplate"): (
        "langchain_core",
        "prompts",
        "chat",
        "AIMessagePromptTemplate",
    ),
    ("langchain_core", "runnables", "RunnableEach"): (
        "langchain_core",
        "runnables",
        "RunnableEach",
    ),
    ("langchain_core", "messages", "system", "SystemMessageChunk"): (
        "langchain_core",
        "messages",
        "system",
        "SystemMessageChunk",
    ),
    ("langchain_core", "prompts", "chat", "SystemMessagePromptTemplate"): (
        "langchain_core",
        "prompts",
        "chat",
        "SystemMessagePromptTemplate",
    ),
    (
        "langchain_core",
        "prompts",
        "few_shot_with_templates",
        "FewShotPromptWithTemplates",
    ): (
        "langchain_core",
        "prompts",
        "few_shot_with_templates",
        "FewShotPromptWithTemplates",
    ),
    ("langchain_core", "output_parsers", "string", "StrOutputParser"): (
        "langchain_core",
        "output_parsers",
        "string",
        "StrOutputParser",
    ),
    ("langchain_core", "outputs", "generation", "GenerationChunk"): (
        "langchain_core",
        "outputs",
        "generation",
        "GenerationChunk",
    ),
    ("langchain_core", "messages", "base", "BaseMessage"): (
        "langchain_core",
        "messages",
        "base",
        "BaseMessage",
    ),
    ("langchain_core", "agents", "AgentFinish"): (
        "langchain_core",
        "agents",
        "AgentFinish",
    ),
    ("langchain_core", "prompts", "chat", "BaseStringMessagePromptTemplate"): (
        "langchain_core",
        "prompts",
        "chat",
        "BaseStringMessagePromptTemplate",
    ),
    ("langchain_core", "prompt_values", "PromptValue"): (
        "langchain_core",
        "prompt_values",
        "PromptValue",
    ),
    ("langchain_core", "runnables", "RunnableBranch"): (
        "langchain_core",
        "runnables",
        "RunnableBranch",
    ),
    ("langchain_core", "runnables", "RunnableWithFallbacks"): (
        "langchain_core",
        "runnables",
        "RunnableWithFallbacks",
    ),
    ("langchain_core", "messages", "human", "HumanMessage"): (
        "langchain_core",
        "messages",
        "human",
        "HumanMessage",
    ),
    ("langchain_core", "output_parsers", "list", "CommaSeparatedListOutputParser"): (
        "langchain_core",
        "output_parsers",
        "list",
        "CommaSeparatedListOutputParser",
    ),
    ("langchain_core", "runnables", "RunnableConfigurableFields"): (
        "langchain_core",
        "runnables",
        "RunnableConfigurableFields",
    ),
    ("langchain_core", "runnables", "RunnableRetry"): (
        "langchain_core",
        "runnables",
        "RunnableRetry",
    ),
    ("langchain_core", "prompts", "base", "BasePromptTemplate"): (
        "langchain_core",
        "prompts",
        "base",
        "BasePromptTemplate",
    ),
    ("langchain_core", "runnables", "RunnableBinding"): (
        "langchain_core",
        "runnables",
        "RunnableBinding",
    ),
    ("langchain_core", "runnables", "RunnableWithMessageHistory"): (
        "langchain_core",
        "runnables",
        "RunnableWithMessageHistory",
    ),
    ("langchain_core", "runnables", "RunnableConfigurableAlternatives"): (
        "langchain_core",
        "runnables",
        "RunnableConfigurableAlternatives",
    ),
    ("langchain_core", "runnables", "RunnableAssign"): (
        "langchain_core",
        "runnables",
        "RunnableAssign",
    ),
    ("langchain_core", "prompts", "string", "StringPromptTemplate"): (
        "langchain_core",
        "prompts",
        "string",
        "StringPromptTemplate",
    ),
    ("langchain_core", "messages", "chat", "ChatMessageChunk"): (
        "langchain_core",
        "messages",
        "chat",
        "ChatMessageChunk",
    ),
    ("langchain_core", "messages", "tool", "ToolMessageChunk"): (
        "langchain_core",
        "messages",
        "tool",
        "ToolMessageChunk",
    ),
    ("langchain", "output_parsers", "combining", "CombiningOutputParser"): (
        "langchain",
        "output_parsers",
        "combining",
        "CombiningOutputParser",
    ),
    ("langchain", "llms", "openai", "BaseOpenAI"): (
        "langchain",
        "llms",
        "openai",
        "BaseOpenAI",
    ),
    ("langchain", "chat_models", "bedrock", "BedrockChat"): (
        "langchain",
        "chat_models",
        "bedrock",
        "BedrockChat",
    ),
    ("langchain", "llms", "openai", "OpenAI"): (
        "langchain",
        "llms",
        "openai",
        "OpenAI",
    ),
    ("langchain", "chat_models", "anthropic", "ChatAnthropic"): (
        "langchain",
        "chat_models",
        "anthropic",
        "ChatAnthropic",
    ),
    ("langchain", "chat_models", "azure_openai", "AzureChatOpenAI"): (
        "langchain",
        "chat_models",
        "azure_openai",
        "AzureChatOpenAI",
    ),
    ("langchain", "chat_models", "vertexai", "ChatVertexAI"): (
        "langchain",
        "chat_models",
        "vertexai",
        "ChatVertexAI",
    ),
    ("langchain", "output_parsers", "regex", "RegexParser"): (
        "langchain",
        "output_parsers",
        "regex",
        "RegexParser",
    ),
    ("langchain", "runnables", "HubRunnable"): (
        "langchain",
        "runnables",
        "HubRunnable",
    ),
    ("langchain", "chat_models", "fireworks", "ChatFireworks"): (
        "langchain",
        "chat_models",
        "fireworks",
        "ChatFireworks",
    ),
    ("langchain", "chat_models", "google_palm", "ChatGooglePalm"): (
        "langchain",
        "chat_models",
        "google_palm",
        "ChatGooglePalm",
    ),
    ("langchain", "llms", "vertexai", "VertexAI"): (
        "langchain",
        "llms",
        "vertexai",
        "VertexAI",
    ),
    ("langchain", "llms", "replicate", "Replicate"): (
        "langchain",
        "llms",
        "replicate",
        "Replicate",
    ),
    (
        "langchain",
        "agents",
        "output_parsers",
        "openai_tools",
        "OpenAIToolAgentAction",
    ): (
        "langchain",
        "agents",
        "output_parsers",
        "openai_tools",
        "OpenAIToolAgentAction",
    ),
    ("langchain", "chains", "llm", "LLMChain"): (
        "langchain",
        "chains",
        "llm",
        "LLMChain",
    ),
    ("langchain", "llms", "fireworks", "Fireworks"): (
        "langchain",
        "llms",
        "fireworks",
        "Fireworks",
    ),
    ("langchain", "chat_models", "openai", "ChatOpenAI"): (
        "langchain",
        "chat_models",
        "openai",
        "ChatOpenAI",
    ),
    ("langchain", "runnables", "OpenAIFunctionsRouter"): (
        "langchain",
        "runnables",
        "OpenAIFunctionsRouter",
    ),
    ("langchain", "llms", "bedrock", "Bedrock"): (
        "langchain",
        "llms",
        "bedrock",
        "Bedrock",
    ),
    ("langchain", "output_parsers", "fix", "OutputFixingParser"): (
        "langchain",
        "output_parsers",
        "fix",
        "OutputFixingParser",
    ),
    ("langchain", "llms", "google_palm", "GooglePalm"): (
        "langchain",
        "llms",
        "google_palm",
        "GooglePalm",
    ),
    ("langchain", "llms", "openai", "AzureOpenAI"): (
        "langchain",
        "llms",
        "openai",
        "AzureOpenAI",
    ),
}


old = {('langchain',
  'agents',
  'openai_assistant',
  'base',
  'OpenAIAssistantAction'): ('langchain',
  'agents',
  'openai_assistant',
  'base',
  'OpenAIAssistantAction'),
 ('langchain',
  'agents',
  'openai_assistant',
  'base',
  'OpenAIAssistantFinish'): ('langchain',
  'agents',
  'openai_assistant',
  'base',
  'OpenAIAssistantFinish'),
 ('langchain',
  'agents',
  'output_parsers',
  'openai_tools',
  'OpenAIToolAgentAction'): ('langchain',
  'agents',
  'output_parsers',
  'openai_tools',
  'OpenAIToolAgentAction'),
 ('langchain',
  'agents',
  'schema',
  'AgentScratchPadChatPromptTemplate'): ('langchain', 'agents', 'schema', 'AgentScratchPadChatPromptTemplate'),
 ('langchain',
  'chains',
  'api',
  'openapi',
  'requests_chain',
  'APIRequesterChain'): ('langchain',
  'chains',
  'api',
  'openapi',
  'requests_chain',
  'APIRequesterChain'),
 ('langchain',
  'chains',
  'api',
  'openapi',
  'response_chain',
  'APIResponderChain'): ('langchain',
  'chains',
  'api',
  'openapi',
  'response_chain',
  'APIResponderChain'),
 ('langchain',
  'chains',
  'conversation',
  'base',
  'ConversationChain'): ('langchain', 'chains', 'conversation', 'base', 'ConversationChain'),
 ('langchain',
  'chains',
  'flare',
  'base',
  'QuestionGeneratorChain'): ('langchain', 'chains', 'flare', 'base', 'QuestionGeneratorChain'),
 ('langchain',
  'chains',
  'flare',
  'base',
  '_OpenAIResponseChain'): ('langchain', 'chains', 'flare', 'base', '_OpenAIResponseChain'),
 ('langchain', 'chains', 'flare', 'base', '_ResponseChain'): ('langchain',
  'chains',
  'flare',
  'base',
  '_ResponseChain'),
 ('langchain', 'chains', 'llm', 'LLMChain'): ('langchain',
  'chains',
  'llm',
  'LLMChain'),
 ('langchain', 'chat_models', 'anthropic', 'ChatAnthropic'): ('langchain',
  'chat_models',
  'anthropic',
  'ChatAnthropic'),
 ('langchain', 'chat_models', 'anyscale', 'ChatAnyscale'): ('langchain',
  'chat_models',
  'anyscale',
  'ChatAnyscale'),
 ('langchain', 'chat_models', 'azure_openai', 'AzureChatOpenAI'): ('langchain',
  'chat_models',
  'azure_openai',
  'AzureChatOpenAI'),
 ('langchain', 'chat_models', 'bedrock', 'BedrockChat'): ('langchain',
  'chat_models',
  'bedrock',
  'BedrockChat'),
 ('langchain', 'chat_models', 'everlyai', 'ChatEverlyAI'): ('langchain',
  'chat_models',
  'everlyai',
  'ChatEverlyAI'),
 ('langchain', 'chat_models', 'fireworks', 'ChatFireworks'): ('langchain',
  'chat_models',
  'fireworks',
  'ChatFireworks'),
 ('langchain', 'chat_models', 'google_palm', 'ChatGooglePalm'): ('langchain',
  'chat_models',
  'google_palm',
  'ChatGooglePalm'),
 ('langchain', 'chat_models', 'jinachat', 'JinaChat'): ('langchain',
  'chat_models',
  'jinachat',
  'JinaChat'),
 ('langchain', 'chat_models', 'konko', 'ChatKonko'): ('langchain',
  'chat_models',
  'konko',
  'ChatKonko'),
 ('langchain', 'chat_models', 'ollama', 'ChatOllama'): ('langchain',
  'chat_models',
  'ollama',
  'ChatOllama'),
 ('langchain', 'chat_models', 'openai', 'ChatOpenAI'): ('langchain',
  'chat_models',
  'openai',
  'ChatOpenAI'),
 ('langchain',
  'chat_models',
  'promptlayer_openai',
  'PromptLayerChatOpenAI'): ('langchain', 'chat_models', 'promptlayer_openai', 'PromptLayerChatOpenAI'),
 ('langchain', 'chat_models', 'vertexai', 'ChatVertexAI'): ('langchain',
  'chat_models',
  'vertexai',
  'ChatVertexAI'),
 ('langchain',
  'document_transformers',
  'embeddings_redundant_filter',
  '_DocumentWithState'): ('langchain',
  'document_transformers',
  'embeddings_redundant_filter',
  '_DocumentWithState'),
 ('langchain',
  'evaluation',
  'comparison',
  'eval_chain',
  'LabeledPairwiseStringEvalChain'): ('langchain',
  'evaluation',
  'comparison',
  'eval_chain',
  'LabeledPairwiseStringEvalChain'),
 ('langchain',
  'evaluation',
  'comparison',
  'eval_chain',
  'PairwiseStringEvalChain'): ('langchain',
  'evaluation',
  'comparison',
  'eval_chain',
  'PairwiseStringEvalChain'),
 ('langchain',
  'evaluation',
  'criteria',
  'eval_chain',
  'CriteriaEvalChain'): ('langchain', 'evaluation', 'criteria', 'eval_chain', 'CriteriaEvalChain'),
 ('langchain',
  'evaluation',
  'criteria',
  'eval_chain',
  'LabeledCriteriaEvalChain'): ('langchain',
  'evaluation',
  'criteria',
  'eval_chain',
  'LabeledCriteriaEvalChain'),
 ('langchain',
  'evaluation',
  'qa',
  'eval_chain',
  'ContextQAEvalChain'): ('langchain', 'evaluation', 'qa', 'eval_chain', 'ContextQAEvalChain'),
 ('langchain',
  'evaluation',
  'qa',
  'eval_chain',
  'CotQAEvalChain'): ('langchain', 'evaluation', 'qa', 'eval_chain', 'CotQAEvalChain'),
 ('langchain', 'evaluation', 'qa', 'eval_chain', 'QAEvalChain'): ('langchain',
  'evaluation',
  'qa',
  'eval_chain',
  'QAEvalChain'),
 ('langchain',
  'evaluation',
  'qa',
  'generate_chain',
  'QAGenerateChain'): ('langchain', 'evaluation', 'qa', 'generate_chain', 'QAGenerateChain'),
 ('langchain',
  'evaluation',
  'scoring',
  'eval_chain',
  'LabeledScoreStringEvalChain'): ('langchain',
  'evaluation',
  'scoring',
  'eval_chain',
  'LabeledScoreStringEvalChain'),
 ('langchain',
  'evaluation',
  'scoring',
  'eval_chain',
  'ScoreStringEvalChain'): ('langchain',
  'evaluation',
  'scoring',
  'eval_chain',
  'ScoreStringEvalChain'),
 ('langchain', 'indexes', '_api', '_HashedDocument'): ('langchain',
  'indexes',
  '_api',
  '_HashedDocument'),
 ('langchain', 'llms', 'anyscale', 'Anyscale'): ('langchain',
  'llms',
  'anyscale',
  'Anyscale'),
 ('langchain', 'llms', 'bedrock', 'Bedrock'): ('langchain',
  'llms',
  'bedrock',
  'Bedrock'),
 ('langchain', 'llms', 'fireworks', 'Fireworks'): ('langchain',
  'llms',
  'fireworks',
  'Fireworks'),
 ('langchain', 'llms', 'google_palm', 'GooglePalm'): ('langchain',
  'llms',
  'google_palm',
  'GooglePalm'),
 ('langchain', 'llms', 'openai', 'AzureOpenAI'): ('langchain',
  'llms',
  'openai',
  'AzureOpenAI'),
 ('langchain', 'llms', 'openai', 'BaseOpenAI'): ('langchain',
  'llms',
  'openai',
  'BaseOpenAI'),
 ('langchain', 'llms', 'openai', 'OpenAI'): ('langchain',
  'llms',
  'openai',
  'OpenAI'),
 ('langchain', 'llms', 'openlm', 'OpenLM'): ('langchain',
  'llms',
  'openlm',
  'OpenLM'),
 ('langchain',
  'llms',
  'promptlayer_openai',
  'PromptLayerOpenAI'): ('langchain', 'llms', 'promptlayer_openai', 'PromptLayerOpenAI'),
 ('langchain', 'llms', 'replicate', 'Replicate'): ('langchain',
  'llms',
  'replicate',
  'Replicate'),
 ('langchain', 'llms', 'tongyi', 'Tongyi'): ('langchain',
  'llms',
  'tongyi',
  'Tongyi'),
 ('langchain', 'llms', 'vertexai', 'VertexAI'): ('langchain',
  'llms',
  'vertexai',
  'VertexAI'),
 ('langchain', 'llms', 'vllm', 'VLLMOpenAI'): ('langchain',
  'llms',
  'vllm',
  'VLLMOpenAI'),
 ('langchain',
  'output_parsers',
  'combining',
  'CombiningOutputParser'): ('langchain', 'output_parsers', 'combining', 'CombiningOutputParser'),
 ('langchain', 'output_parsers', 'fix', 'OutputFixingParser'): ('langchain',
  'output_parsers',
  'fix',
  'OutputFixingParser'),
 ('langchain',
  'output_parsers',
  'list',
  'CommaSeparatedListOutputParser'): ('langchain', 'output_parsers', 'list', 'CommaSeparatedListOutputParser'),
 ('langchain', 'output_parsers', 'regex', 'RegexParser'): ('langchain',
  'output_parsers',
  'regex',
  'RegexParser'),
 ('langchain', 'prompts', 'base', 'StringPromptTemplate'): ('langchain',
  'prompts',
  'base',
  'StringPromptTemplate'),
 ('langchain', 'prompts', 'base', 'StringPromptValue'): ('langchain',
  'prompts',
  'base',
  'StringPromptValue'),
 ('langchain', 'prompts', 'chat', 'AIMessagePromptTemplate'): ('langchain',
  'prompts',
  'chat',
  'AIMessagePromptTemplate'),
 ('langchain', 'prompts', 'chat', 'BaseChatPromptTemplate'): ('langchain',
  'prompts',
  'chat',
  'BaseChatPromptTemplate'),
 ('langchain', 'prompts', 'chat', 'BaseMessagePromptTemplate'): ('langchain',
  'prompts',
  'chat',
  'BaseMessagePromptTemplate'),
 ('langchain',
  'prompts',
  'chat',
  'BaseStringMessagePromptTemplate'): ('langchain', 'prompts', 'chat', 'BaseStringMessagePromptTemplate'),
 ('langchain', 'prompts', 'chat', 'ChatMessagePromptTemplate'): ('langchain',
  'prompts',
  'chat',
  'ChatMessagePromptTemplate'),
 ('langchain', 'prompts', 'chat', 'ChatPromptTemplate'): ('langchain',
  'prompts',
  'chat',
  'ChatPromptTemplate'),
 ('langchain', 'prompts', 'chat', 'ChatPromptValue'): ('langchain',
  'prompts',
  'chat',
  'ChatPromptValue'),
 ('langchain', 'prompts', 'chat', 'ChatPromptValueConcrete'): ('langchain',
  'prompts',
  'chat',
  'ChatPromptValueConcrete'),
 ('langchain', 'prompts', 'chat', 'HumanMessagePromptTemplate'): ('langchain',
  'prompts',
  'chat',
  'HumanMessagePromptTemplate'),
 ('langchain', 'prompts', 'chat', 'MessagesPlaceholder'): ('langchain',
  'prompts',
  'chat',
  'MessagesPlaceholder'),
 ('langchain', 'prompts', 'chat', 'SystemMessagePromptTemplate'): ('langchain',
  'prompts',
  'chat',
  'SystemMessagePromptTemplate'),
 ('langchain',
  'prompts',
  'few_shot_with_templates',
  'FewShotPromptWithTemplates'): ('langchain',
  'prompts',
  'few_shot_with_templates',
  'FewShotPromptWithTemplates'),
 ('langchain', 'prompts', 'pipeline', 'PipelinePromptTemplate'): ('langchain',
  'prompts',
  'pipeline',
  'PipelinePromptTemplate'),
 ('langchain', 'prompts', 'prompt', 'PromptTemplate'): ('langchain',
  'prompts',
  'prompt',
  'PromptTemplate'),
 ('langchain', 'runnables', 'HubRunnable'): ('langchain',
  'runnables',
  'HubRunnable'),
 ('langchain', 'runnables', 'OpenAIFunctionsRouter'): ('langchain',
  'runnables',
  'OpenAIFunctionsRouter'),
 ('langchain', 'schema', 'agent', 'AgentAction'): ('langchain',
  'schema',
  'agent',
  'AgentAction'),
 ('langchain', 'schema', 'agent', 'AgentActionMessageLog'): ('langchain',
  'schema',
  'agent',
  'AgentActionMessageLog'),
 ('langchain', 'schema', 'agent', 'AgentFinish'): ('langchain',
  'schema',
  'agent',
  'AgentFinish'),
 ('langchain', 'schema', 'document', 'Document'): ('langchain',
  'schema',
  'document',
  'Document'),
 ('langchain', 'schema', 'messages', 'AIMessage'): ('langchain',
  'schema',
  'messages',
  'AIMessage'),
 ('langchain', 'schema', 'messages', 'AIMessageChunk'): ('langchain',
  'schema',
  'messages',
  'AIMessageChunk'),
 ('langchain', 'schema', 'messages', 'BaseMessage'): ('langchain',
  'schema',
  'messages',
  'BaseMessage'),
 ('langchain', 'schema', 'messages', 'BaseMessageChunk'): ('langchain',
  'schema',
  'messages',
  'BaseMessageChunk'),
 ('langchain', 'schema', 'messages', 'ChatMessage'): ('langchain',
  'schema',
  'messages',
  'ChatMessage'),
 ('langchain', 'schema', 'messages', 'ChatMessageChunk'): ('langchain',
  'schema',
  'messages',
  'ChatMessageChunk'),
 ('langchain', 'schema', 'messages', 'FunctionMessage'): ('langchain',
  'schema',
  'messages',
  'FunctionMessage'),
 ('langchain', 'schema', 'messages', 'FunctionMessageChunk'): ('langchain',
  'schema',
  'messages',
  'FunctionMessageChunk'),
 ('langchain', 'schema', 'messages', 'HumanMessage'): ('langchain',
  'schema',
  'messages',
  'HumanMessage'),
 ('langchain', 'schema', 'messages', 'HumanMessageChunk'): ('langchain',
  'schema',
  'messages',
  'HumanMessageChunk'),
 ('langchain', 'schema', 'messages', 'SystemMessage'): ('langchain',
  'schema',
  'messages',
  'SystemMessage'),
 ('langchain', 'schema', 'messages', 'SystemMessageChunk'): ('langchain',
  'schema',
  'messages',
  'SystemMessageChunk'),
 ('langchain', 'schema', 'messages', 'ToolMessage'): ('langchain',
  'schema',
  'messages',
  'ToolMessage'),
 ('langchain', 'schema', 'messages', 'ToolMessageChunk'): ('langchain',
  'schema',
  'messages',
  'ToolMessageChunk'),
 ('langchain', 'schema', 'output', 'ChatGeneration'): ('langchain',
  'schema',
  'output',
  'ChatGeneration'),
 ('langchain', 'schema', 'output', 'ChatGenerationChunk'): ('langchain',
  'schema',
  'output',
  'ChatGenerationChunk'),
 ('langchain', 'schema', 'output', 'Generation'): ('langchain',
  'schema',
  'output',
  'Generation'),
 ('langchain', 'schema', 'output', 'GenerationChunk'): ('langchain',
  'schema',
  'output',
  'GenerationChunk'),
 ('langchain', 'schema', 'output_parser', 'StrOutputParser'): ('langchain',
  'schema',
  'output_parser',
  'StrOutputParser'),
 ('langchain', 'schema', 'prompt', 'PromptValue'): ('langchain',
  'schema',
  'prompt',
  'PromptValue'),
 ('langchain',
  'schema',
  'prompt_template',
  'BasePromptTemplate'): ('langchain', 'schema', 'prompt_template', 'BasePromptTemplate'),
 ('langchain', 'schema', 'runnable', 'DynamicRunnable'): ('langchain',
  'schema',
  'runnable',
  'DynamicRunnable'),
 ('langchain', 'schema', 'runnable', 'RouterRunnable'): ('langchain',
  'schema',
  'runnable',
  'RouterRunnable'),
 ('langchain', 'schema', 'runnable', 'RunnableAssign'): ('langchain',
  'schema',
  'runnable',
  'RunnableAssign'),
 ('langchain', 'schema', 'runnable', 'RunnableBinding'): ('langchain',
  'schema',
  'runnable',
  'RunnableBinding'),
 ('langchain', 'schema', 'runnable', 'RunnableBindingBase'): ('langchain',
  'schema',
  'runnable',
  'RunnableBindingBase'),
 ('langchain', 'schema', 'runnable', 'RunnableBranch'): ('langchain',
  'schema',
  'runnable',
  'RunnableBranch'),
 ('langchain',
  'schema',
  'runnable',
  'RunnableConfigurableAlternatives'): ('langchain', 'schema', 'runnable', 'RunnableConfigurableAlternatives'),
 ('langchain',
  'schema',
  'runnable',
  'RunnableConfigurableFields'): ('langchain', 'schema', 'runnable', 'RunnableConfigurableFields'),
 ('langchain', 'schema', 'runnable', 'RunnableEach'): ('langchain',
  'schema',
  'runnable',
  'RunnableEach'),
 ('langchain', 'schema', 'runnable', 'RunnableEachBase'): ('langchain',
  'schema',
  'runnable',
  'RunnableEachBase'),
 ('langchain', 'schema', 'runnable', 'RunnableParallel'): ('langchain',
  'schema',
  'runnable',
  'RunnableParallel'),
 ('langchain', 'schema', 'runnable', 'RunnablePassthrough'): ('langchain',
  'schema',
  'runnable',
  'RunnablePassthrough'),
 ('langchain', 'schema', 'runnable', 'RunnableRetry'): ('langchain',
  'schema',
  'runnable',
  'RunnableRetry'),
 ('langchain', 'schema', 'runnable', 'RunnableSequence'): ('langchain',
  'schema',
  'runnable',
  'RunnableSequence'),
 ('langchain', 'schema', 'runnable', 'RunnableWithFallbacks'): ('langchain',
  'schema',
  'runnable',
  'RunnableWithFallbacks'),
 ('langchain',
  'schema',
  'runnable',
  'RunnableWithMessageHistory'): ('langchain', 'schema', 'runnable', 'RunnableWithMessageHistory')}