# Label PRs (config)
# Automatically applies labels based on changed files and branch patterns

# Core packages
core:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/core/**/*"

langchain-classic:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/langchain/**/*"

langchain:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/langchain_v1/**/*"

cli:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/cli/**/*"

standard-tests:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/standard-tests/**/*"

model-profiles:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/model-profiles/**/*"

text-splitters:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/text-splitters/**/*"

# Partner integrations
integration:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/**/*"

anthropic:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/anthropic/**/*"

chroma:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/chroma/**/*"

deepseek:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/deepseek/**/*"

exa:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/exa/**/*"

fireworks:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/fireworks/**/*"

groq:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/groq/**/*"

huggingface:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/huggingface/**/*"

mistralai:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/mistralai/**/*"

nomic:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/nomic/**/*"

ollama:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/ollama/**/*"

openai:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/openai/**/*"

perplexity:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/perplexity/**/*"

prompty:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/prompty/**/*"

qdrant:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/qdrant/**/*"

xai:
  - changed-files:
      - any-glob-to-any-file:
          - "libs/partners/xai/**/*"

# Infrastructure and DevOps
infra:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
          - "Makefile"
          - ".pre-commit-config.yaml"
          - "scripts/**/*"
          - "docker/**/*"
          - "Dockerfile*"

github_actions:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**/*"
          - ".github/actions/**/*"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pyproject.toml"
          - "uv.lock"
          - "**/requirements*.txt"
          - "**/poetry.lock"

# Documentation
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "**/README*"

