[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --strict-markers --strict-config -vv
markers =
    requires: mark tests as requiring a specific library
    scheduled: mark tests to run in scheduled testing
filterwarnings =
    ignore::langchain_core._api.beta_decorator.LangChainBetaWarning
    ignore::langchain_core._api.deprecation.LangChainDeprecationWarning
    ignore::langchain_core._api.deprecation.LangChainPendingDeprecationWarning