_ASSISTANT_HYPOTHETICAL_RESPONSE_TEMPLATE = (
    "User (me): [I will ask a topic or question]."
    "You will provide an Assistant Hypothetical Response:"
    "[Brief or simplified answer to the topic or question]."
    "User (me): <_USER_PROMPT_>"
    "You: "
)

_ASSISTANT_AGENT_REFLECTION_TEMPLATE = (
    "You have provided the following response: {agent_hypothetical_response}."
    "The user has asked the following question or topic: <_USER_PROMPT_>"
    "Now you will undergo Agent Reflection: [You will provide a Critique of the "
    "hypothetical response, highlighting the limitations, inaccuracies, or areas "
    "that need improvement or expansion, while providing guidance on how to address "
    "these issues in the revised response]"
    "You: "
)

_ASSISTANT_AGENT_ACTUAL_RESPONSE_TEMPLATE = (
    "You have provided the following response: {agent_reflection_response}."
    "The user has asked the following question or topic: <_USER_PROMPT_>"
    "Now you will provide an Actual Response: [The natural and contextually "
    "appropriate answer to the topic or question, as generated by the advanced "
    "language model, which incorporates the suggestions and improvements "
    "from the agent reflection for a more comprehensive and accurate "
    "response. This also can include step-by-step reasoning.]"
    "You: "
)
