labels: [Question]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in LangChain 🦜️🔗!

        Please follow these instructions, fill every question, and do every step. 🙏
        
        We're asking for this because answering questions and solving problems in GitHub takes a lot of time --
        this is time that we cannot spend on adding new features, fixing bugs, writing documentation or reviewing pull requests.

        By asking questions in a structured way (following this) it will be much easier for us to help you.

        There's a high chance that by following this process, you'll find the solution on your own, eliminating the need to submit a question and wait for an answer. 😎

        As there are many questions submitted every day, we will **DISCARD** and close the incomplete ones. 
        
        That will allow us (and others) to focus on helping people like you that follow the whole process. 🤓
        
        Relevant links to check before opening a question to see if your question has already been answered, fixed or
        if there's another way to solve your problem:
        
        [LangChain documentation with the integrated search](https://python.langchain.com/docs/get_started/introduction),
        [API Reference](https://python.langchain.com/api_reference/),
        [GitHub search](https://github.com/langchain-ai/langchain),
        [LangChain Github Discussions](https://github.com/langchain-ai/langchain/discussions),
        [LangChain Github Issues](https://github.com/langchain-ai/langchain/issues?q=is%3Aissue),
        [LangChain ChatBot](https://chat.langchain.com/)
  - type: checkboxes
    id: checks
    attributes:
      label: Checked other resources
      description: Please confirm and check all the following options.
      options:
        - label: I added a very descriptive title to this question.
          required: true
        - label: I searched the LangChain documentation with the integrated search.
          required: true
        - label: I used the GitHub search to find a similar question and didn't find it.
          required: true
  - type: checkboxes
    id: help
    attributes:
      label: Commit to Help
      description: |
        After submitting this, I commit to one of:

          * Read open questions until I find 2 where I can help someone and add a comment to help there.
          * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
          * Once my question is answered, I will mark the answer as "accepted".
      options:
        - label: I commit to help with one of those options 👆
          required: true
  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: |
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with your use case.
        
        If a maintainer can copy it, run it, and see it right away, there's a much higher chance that you'll be able to get help.
        
        **Important!** 
        
        * Use code tags (e.g., ```python ... ```) to correctly [format your code](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting).
        * INCLUDE the language label (e.g. `python`) after the first three backticks to enable syntax highlighting. (e.g., ```python rather than ```).
        * Reduce your code to the minimum required to reproduce the issue if possible. This makes it much easier for others to help you.
        * Avoid screenshots when possible, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.

      placeholder: |
        from langchain_core.runnables import RunnableLambda

        def bad_code(inputs) -> int:
          raise NotImplementedError('For demo purpose')
        
          chain = RunnableLambda(bad_code)
          chain.invoke('Hello!')
      render: python
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        What is the problem, question, or error?

        Write a short description explaining what you are doing, what you expect to happen, and what is currently happening.
      placeholder: |
        * I'm trying to use the `langchain` library to do X.
        * I expect to see Y.
        * Instead, it does Z.
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: |
        Please share your system info with us. 
        
        "pip freeze | grep langchain" 
        platform (windows / linux / mac)
        python version
        
        OR if you're on a recent version of langchain-core you can paste the output of:
        
        python -m langchain_core.sys_info
      placeholder: |
        "pip freeze | grep langchain"
        platform
        python version
        
        Alternatively, if you're on a recent version of langchain-core you can paste the output of:
        
        python -m langchain_core.sys_info
        
        These will only surface LangChain packages, don't forget to include any other relevant
        packages you're using (if you're not sure what's relevant, you can paste the entire output of `pip freeze`).
    validations:
      required: true
