"""Auto-generated model profiles.

DO NOT EDIT THIS FILE MANUALLY.
This file is generated by the langchain-profiles CLI tool.

It contains data derived from the models.dev project.

Source: https://github.com/sst/models.dev
License: MIT License

To update these data, refer to the instructions here:

https://docs.langchain.com/oss/python/langchain/models#updating-or-overwriting-profile-data
"""

from typing import Any

_PROFILES: dict[str, dict[str, Any]] = {
    "accounts/fireworks/models/deepseek-r1-0528": {
        "max_input_tokens": 160000,
        "max_output_tokens": 16384,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": True,
        "tool_calling": True,
    },
    "accounts/fireworks/models/deepseek-v3p1": {
        "max_input_tokens": 163840,
        "max_output_tokens": 163840,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": True,
        "tool_calling": True,
    },
    "accounts/fireworks/models/minimax-m2": {
        "max_input_tokens": 128000,
        "max_output_tokens": 16384,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": True,
        "tool_calling": True,
    },
    "accounts/fireworks/models/deepseek-v3-0324": {
        "max_input_tokens": 160000,
        "max_output_tokens": 16384,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": False,
        "tool_calling": True,
    },
    "accounts/fireworks/models/kimi-k2-instruct": {
        "max_input_tokens": 128000,
        "max_output_tokens": 16384,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": False,
        "tool_calling": True,
    },
    "accounts/fireworks/models/qwen3-235b-a22b": {
        "max_input_tokens": 128000,
        "max_output_tokens": 16384,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": True,
        "tool_calling": True,
    },
    "accounts/fireworks/models/gpt-oss-20b": {
        "max_input_tokens": 131072,
        "max_output_tokens": 32768,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": True,
        "tool_calling": True,
    },
    "accounts/fireworks/models/gpt-oss-120b": {
        "max_input_tokens": 131072,
        "max_output_tokens": 32768,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": True,
        "tool_calling": True,
    },
    "accounts/fireworks/models/glm-4p5-air": {
        "max_input_tokens": 131072,
        "max_output_tokens": 131072,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": True,
        "tool_calling": True,
    },
    "accounts/fireworks/models/qwen3-coder-480b-a35b-instruct": {
        "max_input_tokens": 256000,
        "max_output_tokens": 32768,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": False,
        "tool_calling": True,
    },
    "accounts/fireworks/models/glm-4p5": {
        "max_input_tokens": 131072,
        "max_output_tokens": 131072,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": True,
        "tool_calling": True,
    },
}
