name: "\U0001F41B Bug Report"
description: Report a bug in LangChain. To report a security issue, please instead use the security option (below). For questions, please use the LangChain forum (below).
labels: ["bug"]
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report.

        For usage questions, feature requests and general design questions, please use the [LangChain Forum](https://forum.langchain.com/).

        Check these before submitting to see if your issue has already been reported, fixed or if there's another way to solve your problem:

        * [Documentation](https://docs.langchain.com/oss/python/langchain/overview),
        * [API Reference Documentation](https://reference.langchain.com/python/),
        * [LangChain ChatBot](https://chat.langchain.com/)
        * [GitHub search](https://github.com/langchain-ai/langchain),
        * [LangChain Forum](https://forum.langchain.com/),
  - type: checkboxes
    id: checks
    attributes:
      label: Checked other resources
      description: Please confirm and check all the following options.
      options:
        - label: This is a bug, not a usage question.
          required: true
        - label: I added a clear and descriptive title that summarizes this issue.
          required: true
        - label: I used the GitHub search to find a similar question and didn't find it.
          required: true
        - label: I am sure that this is a bug in LangChain rather than my code.
          required: true
        - label: The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).
          required: true
        - label: This is not related to the langchain-community package.
          required: true
        - label: I posted a self-contained, minimal, reproducible example. A maintainer can copy it and run it AS IS.
          required: true
  - type: checkboxes
    id: package
    attributes:
      label: Package (Required)
      description: |
        Which `langchain` package(s) is this bug related to? Select at least one.

        Note that if the package you are reporting for is not listed here, it is not in this repository (e.g. `langchain-google-genai` is in [`langchain-ai/langchain-google`](https://github.com/langchain-ai/langchain-google/)).

        Please report issues for other packages to their respective repositories.
      options:
        - label: langchain
        - label: langchain-openai
        - label: langchain-anthropic
        - label: langchain-classic
        - label: langchain-core
        - label: langchain-model-profiles
        - label: langchain-tests
        - label: langchain-text-splitters
        - label: langchain-chroma
        - label: langchain-deepseek
        - label: langchain-exa
        - label: langchain-fireworks
        - label: langchain-groq
        - label: langchain-huggingface
        - label: langchain-mistralai
        - label: langchain-nomic
        - label: langchain-ollama
        - label: langchain-perplexity
        - label: langchain-prompty
        - label: langchain-qdrant
        - label: langchain-xai
        - label: Other / not sure / general
  - type: textarea
    id: related
    validations:
      required: false
    attributes:
      label: Related Issues / PRs
      description: |
        If this bug is related to any existing issues or pull requests, please link them here.
      placeholder: |
        * e.g. #123, #456
  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction Steps / Example Code (Python)
      description: |
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with your use case.

        If a maintainer can copy it, run it, and see it right away, there's a much higher chance that you'll be able to get help.

        **Important!**

        * Avoid screenshots, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.
        * Reduce your code to the minimum required to reproduce the issue if possible.

        (This will be automatically formatted into code, so no need for backticks.)
      render: python
      placeholder: |
        from langchain_core.runnables import RunnableLambda

        def bad_code(inputs) -> int:
          raise NotImplementedError('For demo purpose')

          chain = RunnableLambda(bad_code)
          chain.invoke('Hello!')
  - type: textarea
    attributes:
      label: Error Message and Stack Trace (if applicable)
      description: |
        If you are reporting an error, please copy and paste the full error message and
        stack trace.
        (This will be automatically formatted into code, so no need for backticks.)
      render: shell
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        What is the problem, question, or error?

        Write a short description telling what you are doing, what you expect to happen, and what is currently happening.
      placeholder: |
        * I'm trying to use the `langchain` library to do X.
        * I expect to see Y.
        * Instead, it does Z.
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: |
        Please share your system info with us.

        Run the following command in your terminal and paste the output here:

        `python -m langchain_core.sys_info`

        or if you have an existing python interpreter running:

        ```python
        from langchain_core import sys_info
        sys_info.print_sys_info()
        ```
      placeholder: |
        python -m langchain_core.sys_info
    validations:
      required: true
