name: Документация
description: Расскажите как мы можем улучшить документацию GigaChain.
title: "DOC: <Укажите развернутый заголовок после префикса 'DOC: '>"
labels: [03 - Документация]

body:
- type: textarea
  attributes: 
    label: "Проблема с существующей документацией:"
    description: >
      Оставьте ссылку на страницу документации или файл кода, где, по вашему мнению, нужно доработать документацию.

- type: textarea
  attributes:
    label: "Запрос на доработку:"
    description: >
      По возможности подробнее опишите какие темы следует отразить в существующей документации, по вашему мнению.