name: 🔒 Privileged
description: You are a LangChain maintainer, or was asked directly by a maintainer to create an issue here. If not, check the other options.
body:
  - type: markdown
    attributes:
      value: |
        If you are not a LangChain maintainer, employee, or were not asked directly by a maintainer to create an issue, then please start the conversation on the [LangChain Forum](https://forum.langchain.com/) instead.
  - type: checkboxes
    id: privileged
    attributes:
      label: Privileged issue
      description: Confirm that you are allowed to create an issue here.
      options:
        - label: I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.
          required: true
  - type: textarea
    id: content
    attributes:
      label: Issue Content
      description: Add the content of the issue here.
  - type: checkboxes
    id: package
    attributes:
      label: Package (Required)
      description: |
        Please select package(s) that this issue is related to.
      options:
        - label: langchain
        - label: langchain-openai
        - label: langchain-anthropic
        - label: langchain-classic
        - label: langchain-core
        - label: langchain-cli
        - label: langchain-model-profiles
        - label: langchain-tests
        - label: langchain-text-splitters
        - label: langchain-chroma
        - label: langchain-deepseek
        - label: langchain-exa
        - label: langchain-fireworks
        - label: langchain-groq
        - label: langchain-huggingface
        - label: langchain-mistralai
        - label: langchain-nomic
        - label: langchain-ollama
        - label: langchain-perplexity
        - label: langchain-prompty
        - label: langchain-qdrant
        - label: langchain-xai
        - label: Other / not sure / general
