openapi: 3.0.3
servers:
  - url: https://api.spotify.com/v1
info:
  description: |
    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

    In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

    The base URI for all Web API requests is `https://api.spotify.com/v1`.

    Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.
  termsOfService: https://developer.spotify.com/terms/
  title: Spotify Web API
  version: 1.0.0
  x-apisguru-categories:
    - media
  x-logo:
    url: https://logo-core.clearbit.com/spotify.com
  x-origin:
    - format: openapi
      url: https://developer.spotify.com/_data/documentation/web-api/reference/open-api-schema.yml
      version: "3.0"
  x-providerName: spotify.com
paths:
  /albums:
    get:
      description: |
        Get Spotify catalog information for multiple albums identified by their Spotify IDs.
      operationId: get-multiple-albums
      security:
        - oauth_2_0: []
      summary: |
        Get Several Albums
      tags:
        - Albums
      x-spotify-docs-console-url: /console/get-several-albums/
      x-spotify-docs-endpoint-name: Get Multiple Albums
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Albums
    x-spotify-docs-display-name: several-albums
  "/albums/{id}":
    get:
      description: |
        Get Spotify catalog information for a single album.
      operationId: get-an-album
      security:
        - oauth_2_0: []
      summary: |
        Get Album
      tags:
        - Albums
      x-spotify-docs-console-url: /console/get-album/?id=0sNOF9WDwhWunNAHPD3Baj
      x-spotify-docs-endpoint-name: Get an Album
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Albums
    x-spotify-docs-display-name: album
  "/albums/{id}/tracks":
    get:
      description: |
        Get Spotify catalog information about an album’s tracks.
        Optional parameters can be used to limit the number of tracks returned.
      operationId: get-an-albums-tracks
      security:
        - oauth_2_0: []
      summary: |
        Get Album Tracks
      tags:
        - Albums
        - Tracks
      x-spotify-docs-console-url: /console/get-album-tracks/
      x-spotify-docs-endpoint-name: Get an Album's Tracks
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Albums
    x-spotify-docs-display-name: album-tracks
  /artists:
    get:
      description: |
        Get Spotify catalog information for several artists based on their Spotify IDs.
      operationId: get-multiple-artists
      security:
        - oauth_2_0: []
      summary: |
        Get Several Artists
      tags:
        - Artists
      x-spotify-docs-console-url: /console/get-several-artists/?ids=0oSGxfWSnnOXhD2fKuz2Gy,3dBVyJ7JuOMt4GE9607Qin
      x-spotify-docs-endpoint-name: Get Multiple Artists
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Artists
    x-spotify-docs-display-name: several-artists
  "/artists/{id}":
    get:
      description: |
        Get Spotify catalog information for a single artist identified by their unique Spotify ID.
      operationId: get-an-artist
      security:
        - oauth_2_0: []
      summary: |
        Get Artist
      tags:
        - Artists
      x-spotify-docs-console-url: /console/get-artist/?id=0OdUWJ0sBjDrqHygGUXeCF
      x-spotify-docs-endpoint-name: Get an Artist
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Artists
    x-spotify-docs-display-name: artist
  "/artists/{id}/albums":
    get:
      description: |
        Get Spotify catalog information about an artist's albums.
      operationId: get-an-artists-albums
      security:
        - oauth_2_0: []
      summary: |
        Get Artist's Albums
      tags:
        - Artists
        - Albums
      x-spotify-docs-console-url: /console/get-artist-albums/?album_type=single&amp;limit=2&amp;market=ES&amp;id=1vCWHaC5f2uS3yhpwWbIA6
      x-spotify-docs-endpoint-name: Get an Artist's Albums
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Artists
    x-spotify-docs-display-name: artist-albums
  "/artists/{id}/related-artists":
    get:
      description: |
        Get Spotify catalog information about artists similar to a given artist. Similarity is based on analysis of the Spotify community's [listening history](http://news.spotify.com/se/2010/02/03/related-artists/).
      operationId: get-an-artists-related-artists
      security:
        - oauth_2_0: []
      summary: |
        Get Artist's Related Artists
      tags:
        - Artists
      x-spotify-docs-console-url: /console/get-artist-related-artists/?id=43ZHCT0cAZBISjO8DG9PnE
      x-spotify-docs-endpoint-name: Get an Artist's Related Artists
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Artists
    x-spotify-docs-display-name: artist-related-artists
  "/artists/{id}/top-tracks":
    get:
      description: |
        Get Spotify catalog information about an artist's top tracks by country.
      operationId: get-an-artists-top-tracks
      security:
        - oauth_2_0: []
      summary: |
        Get Artist's Top Tracks
      tags:
        - Artists
        - Tracks
      x-spotify-docs-console-url: /console/get-artist-top-tracks/?country=SE&amp;id=43ZHCT0cAZBISjO8DG9PnE
      x-spotify-docs-endpoint-name: Get an Artist's Top Tracks
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Artists
    x-spotify-docs-display-name: artist-top-tracks
  "/audio-analysis/{id}":
    get:
      description: |
        Get a low-level audio analysis for a track in the Spotify catalog. The audio analysis describes the track’s structure and musical content, including rhythm, pitch, and timbre.
      operationId: get-audio-analysis
      security:
        - oauth_2_0: []
      summary: |
        Get Track's Audio Analysis
      tags:
        - Tracks
      x-spotify-docs-console-url: /console/get-audio-analysis-track/?id=06AKEBrKUckW0KREUWRnvT
      x-spotify-docs-endpoint-name: Get Audio Analysis for a Track
    x-spotify-docs-category: Tracks
    x-spotify-docs-display-name: audio-analysis-track
  /audio-features:
    get:
      description: |
        Get audio features for multiple tracks based on their Spotify IDs.
      operationId: get-several-audio-features
      security:
        - oauth_2_0: []
      summary: |
        Get Tracks' Audio Features
      tags:
        - Tracks
      x-spotify-docs-console-url: /console/get-audio-features-several-tracks/?ids=4JpKVNYnVcJ8tuMKjAj50A,2NRANZE9UCmPAS5XVbXL40,24JygzOLM0EmRQeGtFcIcG
      x-spotify-docs-endpoint-name: Get Audio Features for Several Tracks
    x-spotify-docs-category: Tracks
    x-spotify-docs-display-name: audio-features-several-tracks
  "/audio-features/{id}":
    get:
      description: |
        Get audio feature information for a single track identified by its unique
        Spotify ID.
      operationId: get-audio-features
      security:
        - oauth_2_0: []
      summary: |
        Get Track's Audio Features
      tags:
        - Tracks
      x-spotify-docs-console-url: /console/get-audio-features-track/?id=06AKEBrKUckW0KREUWRnvT
      x-spotify-docs-endpoint-name: Get Audio Features for a Track
    x-spotify-docs-category: Tracks
    x-spotify-docs-display-name: audio-features-track
  /audiobooks:
    get:
      description: |
        Get Spotify catalog information for several audiobooks identified by their Spotify IDs.<br />
        **Note: Audiobooks are only available for the US, UK, Ireland, New Zealand and Australia markets.**
      operationId: get-multiple-audiobooks
      security:
        - oauth_2_0: []
      summary: |
        Get Several Audiobooks
      tags:
        - Audiobooks
      x-spotify-docs-console-url: /console/get-several-audiobooks/?ids=5thw29eqjomhIDMY1XKsLk,2IEBhnu61ieYGFRPEJIO40
      x-spotify-docs-endpoint-name: Get Several Audiobooks
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Audiobooks
    x-spotify-docs-display-name: several-audiobooks
  "/audiobooks/{id}":
    get:
      description: |
        Get Spotify catalog information for a single audiobook.<br />
        **Note: Audiobooks are only available for the US, UK, Ireland, New Zealand and Australia markets.**
      operationId: get-an-audiobook
      security:
        - oauth_2_0: []
      summary: |
        Get an Audiobook
      tags:
        - Audiobooks
      x-spotify-docs-console-url: /console/get-audiobook/?id=5thw29eqjomhIDMY1XKsLk
      x-spotify-docs-endpoint-name: Get an Audiobook
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Audiobooks
    x-spotify-docs-display-name: audiobook
  "/audiobooks/{id}/chapters":
    get:
      description: |
        Get Spotify catalog information about an audiobook's chapters.<br />
        **Note: Audiobooks are only available for the US, UK, Ireland, New Zealand and Australia markets.**
      operationId: get-audiobook-chapters
      security:
        - oauth_2_0: []
      summary: |
        Get Audiobook Chapters
      tags:
        - Audiobooks
        - Chapters
      x-spotify-docs-console-url: /console/get-audiobook-chapters/?id=5thw29eqjomhIDMY1XKsLk
      x-spotify-docs-endpoint-name: Get an Audiobook's Chapters
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Audiobooks
    x-spotify-docs-display-name: audiobook-chapters
  /browse/categories:
    get:
      description: |
        Get a list of categories used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).
      operationId: get-categories
      security:
        - oauth_2_0: []
      summary: |
        Get Several Browse Categories
      tags:
        - Categories
      x-spotify-docs-console-url: /console/get-browse-categories/
      x-spotify-docs-endpoint-name: Get All Categories
    x-spotify-docs-category: Browse
    x-spotify-docs-display-name: browse-categories
  "/browse/categories/{category_id}":
    get:
      description: |
        Get a single category used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).
      operationId: get-a-category
      security:
        - oauth_2_0: []
      summary: |
        Get Single Browse Category
      tags:
        - Categories
      x-spotify-docs-console-url: /console/get-browse-category/
      x-spotify-docs-endpoint-name: Get a Category
    x-spotify-docs-category: Browse
    x-spotify-docs-display-name: browse-category
  "/browse/categories/{category_id}/playlists":
    get:
      description: |
        Get a list of Spotify playlists tagged with a particular category.
      operationId: get-a-categories-playlists
      security:
        - oauth_2_0: []
      summary: |
        Get Category's Playlists
      tags:
        - Playlists
        - Categories
      x-spotify-docs-console-url: /console/get-category-playlists/?country=BR&amp;category_id=party&amp;limit=2
      x-spotify-docs-endpoint-name: Get a Category's Playlists
    x-spotify-docs-category: Browse
    x-spotify-docs-display-name: category-playlists
  /browse/featured-playlists:
    get:
      description: |
        Get a list of Spotify featured playlists (shown, for example, on a Spotify player's 'Browse' tab).
      operationId: get-featured-playlists
      security:
        - oauth_2_0: []
      summary: |
        Get Featured Playlists
      tags:
        - Playlists
      x-spotify-docs-console-url: /console/get-featured-playlists/?country=SE&amp;limit=2
      x-spotify-docs-endpoint-name: Get All Featured Playlists
      x-spotify-policy-list:
        - $ref: "#/components/x-spotify-policy/MultipleIntegrations"
    x-spotify-docs-category: Browse
    x-spotify-docs-display-name: featured-playlists
  /browse/new-releases:
    get:
      description: |
        Get a list of new album releases featured in Spotify (shown, for example, on a Spotify player’s “Browse” tab).
      operationId: get-new-releases
      security:
        - oauth_2_0: []
      summary: |
        Get New Releases
      tags:
        - Albums
      x-spotify-docs-console-url: /console/get-new-releases/?country=SE
      x-spotify-docs-endpoint-name: Get All New Releases
      x-spotify-policy-list:
        - $ref: "#/components/x-spotify-policy/MultipleIntegrations"
    x-spotify-docs-category: Browse
    x-spotify-docs-display-name: new-releases
  /chapters:
    get:
      description: |
        Get Spotify catalog information for several chapters identified by their Spotify IDs.<br />
        **Note: Chapters are only available for the US, UK, Ireland, New Zealand and Australia markets.**
      operationId: get-several-chapters
      security:
        - oauth_2_0: []
      summary: |
        Get Several Chapters
      tags:
        - Chapters
      x-spotify-docs-console-url: /console/get-several-chapters/?ids=2i47HuOBSV2XaJNy0NCZXM,2GUbORsUnP1qVVlLwd9DzP
      x-spotify-docs-endpoint-name: Get Several Chapters
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Chapters
    x-spotify-docs-display-name: several-chapters
  "/chapters/{id}":
    get:
      description: |
        Get Spotify catalog information for a single chapter.<br />
        **Note: Chapters are only available for the US, UK, Ireland, New Zealand and Australia markets.**
      operationId: get-a-chapter
      security:
        - oauth_2_0: []
      summary: |
        Get a Chapter
      tags:
        - Chapters
      x-spotify-docs-console-url: /console/get-chapter/?id=2i47HuOBSV2XaJNy0NCZXM
      x-spotify-docs-endpoint-name: Get a Chapter
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Chapters
    x-spotify-docs-display-name: chapters
  /episodes:
    get:
      description: |
        Get Spotify catalog information for several episodes based on their Spotify IDs.
      operationId: get-multiple-episodes
      security:
        - oauth_2_0:
            - user-read-playback-position
      summary: |
        Get Several Episodes
      tags:
        - Episodes
      x-spotify-docs-console-url: /console/get-several-episodes/?ids=77o6BIVlYM3msb4MMIL1jH,0Q86acNRm6V9GYx55SXKwf
      x-spotify-docs-endpoint-name: Get Multiple Episodes
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Episodes
    x-spotify-docs-display-name: several-episodes
  "/episodes/{id}":
    get:
      description: |
        Get Spotify catalog information for a single episode identified by its
        unique Spotify ID.
      operationId: get-an-episode
      security:
        - oauth_2_0:
            - user-read-playback-position
      summary: |
        Get Episode
      tags:
        - Episodes
      x-spotify-docs-console-url: /console/get-episode/?id=512ojhOuo1ktJprKbVcKyQ
      x-spotify-docs-endpoint-name: Get an Episode
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Episodes
    x-spotify-docs-display-name: episode
  /markets:
    get:
      description: |
        Get the list of markets where Spotify is available.
      operationId: get-available-markets
      security:
        - oauth_2_0: []
      summary: |
        Get Available Markets
      tags:
        - Markets
      x-spotify-docs-console-url: /console/get-available-markets/
      x-spotify-docs-endpoint-name: Get Available Markets
    x-spotify-docs-category: Markets
    x-spotify-docs-display-name: available-markets
  /me:
    get:
      description: |
        Get detailed profile information about the current user (including the
        current user's username).
      operationId: get-current-users-profile
      security:
        - oauth_2_0:
            - user-read-private
            - user-read-email
      summary: |
        Get Current User's Profile
      tags:
        - Users
      x-spotify-docs-console-url: /console/get-current-user/
      x-spotify-docs-endpoint-name: Get Current User's Profile
    x-spotify-docs-category: Users Profile
    x-spotify-docs-display-name: current-user
  /me/albums:
    delete:
      description: |
        Remove one or more albums from the current user's 'Your Music' library.
      operationId: remove-albums-user
      security:
        - oauth_2_0:
            - user-library-modify
      summary: |
        Remove Users' Saved Albums
      tags:
        - Albums
        - Library
      x-spotify-docs-console-url: /console/delete-current-user-saved-albums/?ids=07bYtmE3bPsLB6ZbmmFi8d%2C48JYNjh7GMie6NjqYHMmtT%2C27cZdqrQiKt3IT00338dws
      x-spotify-docs-endpoint-name: Remove Albums for Current User
    get:
      description: |
        Get a list of the albums saved in the current Spotify user's 'Your Music' library.
      operationId: get-users-saved-albums
      security:
        - oauth_2_0:
            - user-library-read
      summary: |
        Get User's Saved Albums
      tags:
        - Albums
        - Library
      x-spotify-docs-console-url: /console/get-current-user-saved-albums/?limit=1
      x-spotify-docs-endpoint-name: Get User's Saved Albums
    put:
      description: |
        Save one or more albums to the current user's 'Your Music' library.
      operationId: save-albums-user
      security:
        - oauth_2_0:
            - user-library-modify
      summary: |
        Save Albums for Current User
      tags:
        - Albums
        - Library
      x-spotify-docs-console-url: /console/put-current-user-saved-albums/?ids=07bYtmE3bPsLB6ZbmmFi8d%2C48JYNjh7GMie6NjqYHMmtT%2C27cZdqrQiKt3IT00338dws
      x-spotify-docs-endpoint-name: Save Albums for Current User
    x-spotify-docs-category: Library
    x-spotify-docs-display-name: current-user-saved-albums
  /me/albums/contains:
    get:
      description: |
        Check if one or more albums is already saved in the current Spotify user's 'Your Music' library.
      operationId: check-users-saved-albums
      security:
        - oauth_2_0:
            - user-library-read
      summary: |
        Check User's Saved Albums
      tags:
        - Albums
        - Library
      x-spotify-docs-console-url: /console/get-current-user-contains-saved-albums/?ids=0pJJgBzj26qnE1nSQUxaB0%2C5ZAKzV4ZIa5Gt7z29OYHv0
      x-spotify-docs-endpoint-name: Check User's Saved Albums
    x-spotify-docs-category: Library
    x-spotify-docs-display-name: current-user-contains-saved-albums
  /me/audiobooks:
    delete:
      description: |
        Remove one or more audiobooks from the Spotify user's library.
      operationId: remove-audiobooks-user
      security:
        - oauth_2_0:
            - user-library-modify
      summary: |
        Remove User's Saved Audiobooks
      tags:
        - Audiobooks
        - Library
      x-spotify-docs-console-url: /console/delete-current-user-saved-audiobooks/?ids=07bYtmE3bPsLB6ZbmmFi8d%2C48JYNjh7GMie6NjqYHMmtT%2C27cZdqrQiKt3IT00338dws
      x-spotify-docs-endpoint-name: Remove Audiobooks for Current User
    get:
      description: |
        Get a list of the audiobooks saved in the current Spotify user's 'Your Music' library.
      operationId: get-users-saved-audiobooks
      security:
        - oauth_2_0:
            - user-library-read
      summary: |
        Get User's Saved Audiobooks
      tags:
        - Audiobooks
        - Library
      x-spotify-docs-console-url: /console/get-current-user-saved-audiobooks/?limit=1
      x-spotify-docs-endpoint-name: Get User's Saved Audiobooks
    put:
      description: |
        Save one or more audiobooks to the current Spotify user's library.
      operationId: save-audiobooks-user
      security:
        - oauth_2_0:
            - user-library-modify
      summary: |
        Save Audiobooks for Current User
      tags:
        - Audiobooks
        - Library
      x-spotify-docs-console-url: /console/put-current-user-saved-audiobooks/?ids=07bYtmE3bPsLB6ZbmmFi8d%2C48JYNjh7GMie6NjqYHMmtT%2C27cZdqrQiKt3IT00338dws
      x-spotify-docs-endpoint-name: Save Audiobooks for Current User
    x-spotify-docs-category: Library
    x-spotify-docs-display-name: current-user-saved-audiobooks
  /me/audiobooks/contains:
    get:
      description: |
        Check if one or more audiobooks are already saved in the current Spotify user's library.
      operationId: check-users-saved-audiobooks
      security:
        - oauth_2_0:
            - user-library-read
      summary: |
        Check User's Saved Audiobooks
      tags:
        - Audiobooks
        - Library
      x-spotify-docs-console-url: /console/get-current-user-contains-saved-audiobooks/?ids=0pJJgBzj26qnE1nSQUxaB0%2C5ZAKzV4ZIa5Gt7z29OYHv0
      x-spotify-docs-endpoint-name: Check User's Saved Audiobooks
    x-spotify-docs-category: Library
    x-spotify-docs-display-name: current-user-contains-saved-audiobooks
  /me/episodes:
    delete:
      description: |
        Remove one or more episodes from the current user's library.<br/>
        This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
      operationId: remove-episodes-user
      security:
        - oauth_2_0:
            - user-library-modify
      summary: |
        Remove User's Saved Episodes
      tags:
        - Episodes
        - Library
      x-spotify-docs-console-url: /console/delete-current-user-saved-episodes/?ids=77o6BIVlYM3msb4MMIL1jH%2C0Q86acNRm6V9GYx55SXKwf
      x-spotify-docs-endpoint-name: Remove User's Saved Episodes
    get:
      description: |
        Get a list of the episodes saved in the current Spotify user's library.<br/>
        This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
      operationId: get-users-saved-episodes
      security:
        - oauth_2_0:
            - user-library-read
            - user-read-playback-position
      summary: |
        Get User's Saved Episodes
      tags:
        - Episodes
        - Library
      x-spotify-docs-console-url: /console/get-current-user-saved-episodes/
      x-spotify-docs-endpoint-name: Get User's Saved Episodes
    put:
      description: |
        Save one or more episodes to the current user's library.<br/>
        This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
      operationId: save-episodes-user
      security:
        - oauth_2_0:
            - user-library-modify
      summary: |
        Save Episodes for Current User
      tags:
        - Episodes
        - Library
      x-spotify-docs-console-url: /console/put-current-user-saved-episodes/?ids=77o6BIVlYM3msb4MMIL1jH%2C0Q86acNRm6V9GYx55SXKwf
      x-spotify-docs-endpoint-name: Save Episodes for Current User
    x-spotify-docs-category: Library
    x-spotify-docs-display-name: current-user-saved-episodes
  /me/episodes/contains:
    get:
      description: |
        Check if one or more episodes is already saved in the current Spotify user's 'Your Episodes' library.<br/>
        This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)..
      operationId: check-users-saved-episodes
      security:
        - oauth_2_0:
            - user-library-read
      summary: |
        Check User's Saved Episodes
      tags:
        - Episodes
        - Library
      x-spotify-docs-console-url: /console/get-current-user-contains-saved-episodes/?ids=77o6BIVlYM3msb4MMIL1jH%2C0Q86acNRm6V9GYx55SXKwf
      x-spotify-docs-endpoint-name: Check User's Saved Episodes
    x-spotify-docs-category: Library
    x-spotify-docs-display-name: current-user-contains-saved-episodes
  /me/following:
    delete:
      description: |
        Remove the current user as a follower of one or more artists or other Spotify users.
      operationId: unfollow-artists-users
      security:
        - oauth_2_0:
            - user-follow-modify
      summary: |
        Unfollow Artists or Users
      tags:
        - Users
        - Artists
        - Library
      x-spotify-docs-console-url: /console/delete-following/?type=user&amp;ids=exampleuser01
      x-spotify-docs-endpoint-name: Unfollow Artists or Users
    get:
      description: |
        Get the current user's followed artists.
      operationId: get-followed
      security:
        - oauth_2_0:
            - user-follow-read
      summary: |
        Get Followed Artists
      tags:
        - Users
        - Library
        - Artists
      x-spotify-docs-console-url: /console/get-following/?type=artist&amp;limit=20
      x-spotify-docs-endpoint-name: Get User's Followed Artists
    put:
      description: |
        Add the current user as a follower of one or more artists or other Spotify users.
      operationId: follow-artists-users
      security:
        - oauth_2_0:
            - user-follow-modify
      summary: |
        Follow Artists or Users
      tags:
        - Users
        - Artists
        - Library
      x-spotify-docs-console-url: /console/put-following/?type=user&amp;ids=exampleuser01
      x-spotify-docs-endpoint-name: Follow Artists or Users
    x-spotify-docs-category: Follow
    x-spotify-docs-display-name: following
  /me/following/contains:
    get:
      description: |
        Check to see if the current user is following one or more artists or other Spotify users.
      operationId: check-current-user-follows
      security:
        - oauth_2_0:
            - user-follow-read
      summary: |
        Check If User Follows Artists or Users
      tags:
        - Users
        - Artists
        - Library
      x-spotify-docs-console-url: /console/get-following-contains/?type=user&amp;ids=exampleuser01
      x-spotify-docs-endpoint-name: Get Following State for Artists/Users
    x-spotify-docs-category: Follow
    x-spotify-docs-display-name: following-contains
  /me/player:
    get:
      description: |
        Get information about the user’s current playback state, including track or episode, progress, and active device.
      operationId: get-information-about-the-users-current-playback
      security:
        - oauth_2_0:
            - user-read-playback-state
      summary: |
        Get Playback State
      tags:
        - Player
      x-spotify-docs-console-url: /console/get-user-player/
      x-spotify-docs-endpoint-name: Get Information About The User's Current Playback
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/playerPolicyList"
    put:
      description: |
        Transfer playback to a new device and determine if it should start playing.
      operationId: transfer-a-users-playback
      security:
        - oauth_2_0:
            - user-modify-playback-state
      summary: |
        Transfer Playback
      tags:
        - Player
      x-spotify-docs-console-url: /console/put-user-player
      x-spotify-docs-endpoint-name: Transfer a User's Playback
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/playerPolicyList"
    x-spotify-docs-category: Player
    x-spotify-docs-display-name: user-player
  /me/player/currently-playing:
    get:
      description: |
        Get the object currently being played on the user's Spotify account.
      operationId: get-the-users-currently-playing-track
      security:
        - oauth_2_0:
            - user-read-currently-playing
      summary: |
        Get Currently Playing Track
      tags:
        - Player
      x-spotify-docs-console-url: /console/get-users-currently-playing-track/
      x-spotify-docs-endpoint-name: Get the User's Currently Playing Track
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/playerPolicyList"
    x-spotify-docs-category: Player
    x-spotify-docs-display-name: users-currently-playing-track
  /me/player/devices:
    get:
      description: |
        Get information about a user’s available devices.
      operationId: get-a-users-available-devices
      security:
        - oauth_2_0:
            - user-read-playback-state
      summary: |
        Get Available Devices
      tags:
        - Player
      x-spotify-docs-console-url: /console/get-users-available-devices/
      x-spotify-docs-endpoint-name: Get a User's Available Devices
    x-spotify-docs-category: Player
    x-spotify-docs-display-name: users-available-devices
  /me/player/next:
    post:
      description: |
        Skips to next track in the user’s queue.
      operationId: skip-users-playback-to-next-track
      security:
        - oauth_2_0:
            - user-modify-playback-state
      summary: |
        Skip To Next
      tags:
        - Player
      x-spotify-docs-console-url: /console/post-next/
      x-spotify-docs-endpoint-name: Skip User’s Playback To Next Track
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/playerPolicyList"
    x-spotify-docs-category: Player
    x-spotify-docs-display-name: next
  /me/player/pause:
    put:
      description: |
        Pause playback on the user's account.
      operationId: pause-a-users-playback
      security:
        - oauth_2_0:
            - user-modify-playback-state
      summary: |
        Pause Playback
      tags:
        - Player
      x-spotify-docs-console-url: /console/put-pause/
      x-spotify-docs-endpoint-name: Pause a User's Playback
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/playerPolicyList"
    x-spotify-docs-category: Player
    x-spotify-docs-display-name: pause
  /me/player/play:
    put:
      description: |
        Start a new context or resume current playback on the user's active device.
      operationId: start-a-users-playback
      security:
        - oauth_2_0:
            - user-modify-playback-state
      summary: |
        Start/Resume Playback
      tags:
        - Player
      x-spotify-docs-console-url: /console/put-play/
      x-spotify-docs-endpoint-name: Start/Resume a User's Playback
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/playerPolicyList"
    x-spotify-docs-category: Player
    x-spotify-docs-display-name: play
  /me/player/previous:
    post:
      description: |
        Skips to previous track in the user’s queue.
      operationId: skip-users-playback-to-previous-track
      security:
        - oauth_2_0:
            - user-modify-playback-state
      summary: |
        Skip To Previous
      tags:
        - Player
      x-spotify-docs-console-url: /console/post-previous/
      x-spotify-docs-endpoint-name: Skip User’s Playback To Previous Track
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/playerPolicyList"
    x-spotify-docs-category: Player
    x-spotify-docs-display-name: previous
  /me/player/queue:
    get:
      description: |
        Get the list of objects that make up the user's queue.
      operationId: get-queue
      security:
        - oauth_2_0:
            - user-read-playback-state
      summary: |
        Get the User's Queue
      tags:
        - Player
      x-spotify-docs-console-url: /console/get-queue/
      x-spotify-docs-endpoint-name: Get the User's Queue
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/playerPolicyList"
    post:
      description: |
        Add an item to the end of the user's current playback queue.
      operationId: add-to-queue
      security:
        - oauth_2_0:
            - user-modify-playback-state
      summary: |
        Add Item to Playback Queue
      tags:
        - Player
      x-spotify-docs-console-url: /console/post-queue/
      x-spotify-docs-endpoint-name: Add an item to queue
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/playerPolicyList"
    x-spotify-docs-category: Player
    x-spotify-docs-display-name: queue
  /me/player/recently-played:
    get:
      description: |
        Get tracks from the current user's recently played tracks.
        _**Note**: Currently doesn't support podcast episodes._
      operationId: get-recently-played
      security:
        - oauth_2_0:
            - user-read-recently-played
      summary: |
        Get Recently Played Tracks
      tags:
        - Player
      x-spotify-docs-console-url: /console/get-recently-played/
      x-spotify-docs-endpoint-name: Get Current User's Recently Played Tracks
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/playerPolicyList"
    x-spotify-docs-category: Player
    x-spotify-docs-display-name: recently-played
  /me/player/repeat:
    put:
      description: |
        Set the repeat mode for the user's playback. Options are repeat-track,
        repeat-context, and off.
      operationId: set-repeat-mode-on-users-playback
      security:
        - oauth_2_0:
            - user-modify-playback-state
      summary: |
        Set Repeat Mode
      tags:
        - Player
      x-spotify-docs-console-url: /console/put-repeat/
      x-spotify-docs-endpoint-name: Set Repeat Mode On User’s Playback
    x-spotify-docs-category: Player
    x-spotify-docs-display-name: repeat
  /me/player/seek:
    put:
      description: |
        Seeks to the given position in the user’s currently playing track.
      operationId: seek-to-position-in-currently-playing-track
      security:
        - oauth_2_0:
            - user-modify-playback-state
      summary: |
        Seek To Position
      tags:
        - Player
      x-spotify-docs-console-url: /console/put-seek/
      x-spotify-docs-endpoint-name: Seek To Position In Currently Playing Track
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/playerPolicyList"
    x-spotify-docs-category: Player
    x-spotify-docs-display-name: seek
  /me/player/shuffle:
    put:
      description: |
        Toggle shuffle on or off for user’s playback.
      operationId: toggle-shuffle-for-users-playback
      security:
        - oauth_2_0:
            - user-modify-playback-state
      summary: |
        Toggle Playback Shuffle
      tags:
        - Player
      x-spotify-docs-console-url: /console/put-shuffle/?state=true
      x-spotify-docs-endpoint-name: Toggle Shuffle For User’s Playback
    x-spotify-docs-category: Player
    x-spotify-docs-display-name: shuffle
  /me/player/volume:
    put:
      description: |
        Set the volume for the user’s current playback device.
      operationId: set-volume-for-users-playback
      security:
        - oauth_2_0:
            - user-modify-playback-state
      summary: |
        Set Playback Volume
      tags:
        - Player
      x-spotify-docs-console-url: /console/put-volume/
      x-spotify-docs-endpoint-name: Set Volume For User's Playback
    x-spotify-docs-category: Player
    x-spotify-docs-display-name: volume
  /me/playlists:
    get:
      description: |
        Get a list of the playlists owned or followed by the current Spotify
        user.
      operationId: get-a-list-of-current-users-playlists
      security:
        - oauth_2_0:
            - playlist-read-private
      summary: |
        Get Current User's Playlists
      tags:
        - Playlists
        - Library
      x-spotify-docs-console-url: /console/get-current-user-playlists/
      x-spotify-docs-endpoint-name: Get a List of Current User's Playlists
    x-spotify-docs-category: Playlists
    x-spotify-docs-display-name: current-user-playlists
  /me/shows:
    delete:
      description: |
        Delete one or more shows from current Spotify user's library.
      operationId: remove-shows-user
      security:
        - oauth_2_0:
            - user-library-modify
      summary: |
        Remove User's Saved Shows
      tags:
        - Shows
        - Library
      x-spotify-docs-console-url: /console/delete-current-user-saved-shows/?ids=5AvwZVawapvyhJUIx71pdJ%2C6ups0LMt1G8n81XLlkbsPo%2C5AvwZVawapvyhJUIx71pdJ
      x-spotify-docs-endpoint-name: Remove User's Saved Shows
    get:
      description: |
        Get a list of shows saved in the current Spotify user's library. Optional parameters can be used to limit the number of shows returned.
      operationId: get-users-saved-shows
      security:
        - oauth_2_0:
            - user-library-read
      summary: |
        Get User's Saved Shows
      tags:
        - Shows
        - Library
      x-spotify-docs-console-url: /console/get-current-user-saved-shows/
      x-spotify-docs-endpoint-name: Get User's Saved Shows
    put:
      description: |
        Save one or more shows to current Spotify user's library.
      operationId: save-shows-user
      security:
        - oauth_2_0:
            - user-library-modify
      summary: |
        Save Shows for Current User
      tags:
        - Shows
        - Library
      x-spotify-docs-console-url: /console/put-current-user-saved-shows/?ids=5AvwZVawapvyhJUIx71pdJ%2C6ups0LMt1G8n81XLlkbsPo%2C5AvwZVawapvyhJUIx71pdJ
      x-spotify-docs-endpoint-name: Save Shows for Current User
    x-spotify-docs-category: Library
    x-spotify-docs-display-name: current-user-saved-shows
  /me/shows/contains:
    get:
      description: |
        Check if one or more shows is already saved in the current Spotify user's library.
      operationId: check-users-saved-shows
      security:
        - oauth_2_0:
            - user-library-read
      summary: |
        Check User's Saved Shows
      tags:
        - Shows
        - Library
      x-spotify-docs-console-url: /console/get-current-user-contains-saved-shows/?ids=5AvwZVawapvyhJUIx71pdJ%2C6ups0LMt1G8n81XLlkbsPo%2C5AvwZVawapvyhJUIx71pdJ
      x-spotify-docs-endpoint-name: Check User's Saved Shows
    x-spotify-docs-category: Library
    x-spotify-docs-display-name: current-user-contains-saved-shows
  "/me/top/{type}":
    get:
      description: |
        Get the current user's top artists or tracks based on calculated affinity.
      operationId: get-users-top-artists-and-tracks
      security:
        - oauth_2_0:
            - user-top-read
      summary: |
        Get User's Top Items
      tags:
        - Users
        - Tracks
        - Library
      x-spotify-docs-console-url: /console/get-current-user-top-artists-and-tracks/?type=artists
      x-spotify-docs-endpoint-name: Get a User's Top Artists and Tracks
    x-spotify-docs-category: Personalization
    x-spotify-docs-display-name: current-user-top-artists-and-tracks
  /me/tracks:
    delete:
      description: |
        Remove one or more tracks from the current user's 'Your Music' library.
      operationId: remove-tracks-user
      security:
        - oauth_2_0:
            - user-library-modify
      summary: |
        Remove User's Saved Tracks
      tags:
        - Tracks
        - Library
      x-spotify-docs-console-url: /console/delete-current-user-saved-tracks/?ids=7ouMYWpwJ422jRcDASZB7P%2C4VqPOruhp5EdPBeR92t6lQ%2C2takcwOaAZWiXQijPHIx7B
      x-spotify-docs-endpoint-name: Remove User's Saved Tracks
    get:
      description: |
        Get a list of the songs saved in the current Spotify user's 'Your Music' library.
      operationId: get-users-saved-tracks
      security:
        - oauth_2_0:
            - user-library-read
      summary: |
        Get User's Saved Tracks
      tags:
        - Tracks
        - Library
      x-spotify-docs-console-url: /console/get-current-user-saved-tracks/
      x-spotify-docs-endpoint-name: Get User's Saved Tracks
    put:
      description: |
        Save one or more tracks to the current user's 'Your Music' library.
      operationId: save-tracks-user
      security:
        - oauth_2_0:
            - user-library-modify
      summary: |
        Save Tracks for Current User
      tags:
        - Tracks
        - Library
      x-spotify-docs-console-url: /console/put-current-user-saved-tracks/?ids=7ouMYWpwJ422jRcDASZB7P%2C4VqPOruhp5EdPBeR92t6lQ%2C2takcwOaAZWiXQijPHIx7B
      x-spotify-docs-endpoint-name: Save Tracks for User
    x-spotify-docs-category: Library
    x-spotify-docs-display-name: current-user-saved-tracks
  /me/tracks/contains:
    get:
      description: |
        Check if one or more tracks is already saved in the current Spotify user's 'Your Music' library.
      operationId: check-users-saved-tracks
      security:
        - oauth_2_0:
            - user-library-read
      summary: |
        Check User's Saved Tracks
      tags:
        - Tracks
        - Library
      x-spotify-docs-console-url: /console/get-current-user-contains-saved-tracks/?ids=0udZHhCi7p1YzMlvI4fXoK%2C3SF5puV5eb6bgRSxBeMOk9
      x-spotify-docs-endpoint-name: Check User's Saved Tracks
    x-spotify-docs-category: Library
    x-spotify-docs-display-name: current-user-contains-saved-tracks
  "/playlists/{playlist_id}":
    get:
      description: |
        Get a playlist owned by a Spotify user.
      operationId: get-playlist
      security:
        - oauth_2_0: []
      summary: |
        Get Playlist
      tags:
        - Playlists
      x-spotify-docs-console-url: /console/get-playlist/?playlist_id=59ZbFPES4DQwEjBpWHzrtC&amp;user_id=spotify
      x-spotify-docs-endpoint-name: Get a Playlist
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    put:
      description: |
        Change a playlist's name and public/private state. (The user must, of
        course, own the playlist.)
      operationId: change-playlist-details
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
      summary: |
        Change Playlist Details
      tags:
        - Playlists
        - Library
      x-spotify-docs-console-url: /console/put-playlist/
      x-spotify-docs-endpoint-name: Change a Playlist's Details
    x-spotify-docs-category: Playlists
    x-spotify-docs-display-name: playlist
  "/playlists/{playlist_id}/followers":
    delete:
      description: |
        Remove the current user as a follower of a playlist.
      operationId: unfollow-playlist
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
      summary: |
        Unfollow Playlist
      tags:
        - Users
        - Playlists
      x-spotify-docs-console-url: /console/delete-playlist-followers/?playlist_id=2v3iNvBX8Ay1Gt2uXtUKUT&amp;user_id=jmperezperez
      x-spotify-docs-endpoint-name: Unfollow Playlist
    put:
      description: |
        Add the current user as a follower of a playlist.
      operationId: follow-playlist
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
      summary: |
        Follow Playlist
      tags:
        - Users
        - Playlists
      x-spotify-docs-console-url: /console/put-playlist-followers/?playlist_id=2v3iNvBX8Ay1Gt2uXtUKUT&amp;body-json=%7B%0D%0A++%22public%22%3A+true%0D%0A%7D&amp;user_id=jmperezperez
      x-spotify-docs-endpoint-name: Follow a Playlist
    x-spotify-docs-category: Follow
    x-spotify-docs-display-name: playlist-followers
  "/playlists/{playlist_id}/followers/contains":
    get:
      description: |
        Check to see if one or more Spotify users are following a specified playlist.
      operationId: check-if-user-follows-playlist
      security:
        - oauth_2_0: []
      summary: |
        Check if Users Follow Playlist
      tags:
        - Users
        - Playlists
      x-spotify-docs-console-url: /console/get-playlist-followers-contains/?ids=possan,elogain&amp;user_id=jmperezperez&amp;playlist_id=2v3iNvBX8Ay1Gt2uXtUKUT
      x-spotify-docs-endpoint-name: Check if Users Follow a Playlist
    x-spotify-docs-category: Follow
    x-spotify-docs-display-name: playlist-followers-contains
  "/playlists/{playlist_id}/images":
    get:
      description: |
        Get the current image associated with a specific playlist.
      operationId: get-playlist-cover
      security:
        - oauth_2_0: []
      summary: |
        Get Playlist Cover Image
      tags:
        - Playlists
      x-spotify-docs-console-url: /console/get-playlist-images?playlist_id=3cEYpjA9oz9GiPac4AsH4n
      x-spotify-docs-endpoint-name: Get a Playlist Cover Image
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    put:
      description: |
        Replace the image used to represent a specific playlist.
      operationId: upload-custom-playlist-cover
      security:
        - oauth_2_0:
            - ugc-image-upload
            - playlist-modify-public
            - playlist-modify-private
      summary: |
        Add Custom Playlist Cover Image
      tags:
        - Playlists
      x-spotify-docs-console-url: /console/put-playlist-images?playlist_id=3cEYpjA9oz9GiPac4AsH4n
      x-spotify-docs-endpoint-name: Upload a Custom Playlist Cover Image
    x-spotify-docs-category: Playlists
    x-spotify-docs-display-name: playlist-images
  "/playlists/{playlist_id}/tracks":
    delete:
      description: |
        Remove one or more items from a user's playlist.
      operationId: remove-tracks-playlist
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
      summary: |
        Remove Playlist Items
      tags:
        - Playlists
        - Tracks
      x-spotify-docs-console-url: /console/delete-playlist-tracks/
      x-spotify-docs-endpoint-name: Remove Items from a Playlist
    get:
      description: |
        Get full details of the items of a playlist owned by a Spotify user.
      operationId: get-playlists-tracks
      security:
        - oauth_2_0:
            - playlist-read-private
      summary: |
        Get Playlist Items
      tags:
        - Playlists
        - Tracks
      x-spotify-docs-console-url: /console/get-playlist-tracks/?playlist_id=21THa8j9TaSGuXYNBU5tsC&amp;user_id=spotify_espa%C3%B1a
      x-spotify-docs-endpoint-name: Get a Playlist's Items
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    post:
      description: |
        Add one or more items to a user's playlist.
      operationId: add-tracks-to-playlist
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
      summary: |
        Add Items to Playlist
      tags:
        - Playlists
        - Tracks
      x-spotify-docs-console-url: /console/post-playlist-tracks/
      x-spotify-docs-endpoint-name: Add Items to a Playlist
    put:
      description: |
        Either reorder or replace items in a playlist depending on the request's parameters.
        To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request's body.
        To replace items, include `uris` as either a query parameter or in the request's body.
        Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.
        <br/>
        **Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters.
        These operations can't be applied together in a single request.
      operationId: reorder-or-replace-playlists-tracks
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
      summary: |
        Update Playlist Items
      tags:
        - Playlists
        - Tracks
      x-spotify-docs-console-url: /console/put-playlist-tracks/
      x-spotify-docs-endpoint-name: Reorder or Replace a Playlist's Items
    x-spotify-docs-category: Playlists
    x-spotify-docs-display-name: playlist-tracks
  /recommendations:
    get:
      description: |
        Recommendations are generated based on the available information for a given seed entity and matched against similar artists and tracks. If there is sufficient information about the provided seeds, a list of tracks will be returned together with pool size details.

        For artists and tracks that are very new or obscure there might not be enough data to generate a list of tracks.
      operationId: get-recommendations
      security:
        - oauth_2_0: []
      summary: |
        Get Recommendations
      tags:
        - Tracks
      x-spotify-docs-console-url: /console/get-recommendations/?seed_artists=4NHQUGzhtTLFvgF5SZesLK&amp;seed_tracks=0c6xIDDpzE81m2q797ordA&amp;min_energy=0.4&amp;min_popularity=50&amp;market=US
      x-spotify-docs-endpoint-name: Get Recommendations
    x-spotify-docs-category: Browse
    x-spotify-docs-display-name: recommendations
  /recommendations/available-genre-seeds:
    get:
      description: |
        Retrieve a list of available genres seed parameter values for [recommendations](/documentation/web-api/reference/get-recommendations).
      operationId: get-recommendation-genres
      security:
        - oauth_2_0: []
      summary: |
        Get Available Genre Seeds
      tags:
        - Genres
      x-spotify-docs-console-url: /console/get-available-genre-seeds/
      x-spotify-docs-endpoint-name: Get Recommendation Genres
    x-spotify-docs-category: Browse
    x-spotify-docs-display-name: available-genre-seeds
  /search:
    get:
      description: |
        Get Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or audiobooks
        that match a keyword string.<br />
        **Note: Audiobooks are only available for the US, UK, Ireland, New Zealand and Australia markets.**
      operationId: search
      security:
        - oauth_2_0: []
      summary: |
        Search for Item
      tags:
        - Search
      x-spotify-docs-console-url: /console/get-search-item/?q=tania+bowra&amp;type=artist
      x-spotify-docs-endpoint-name: Search for an Item
    x-spotify-docs-category: Search
    x-spotify-docs-display-name: search-item
  /shows:
    get:
      description: |
        Get Spotify catalog information for several shows based on their Spotify IDs.
      operationId: get-multiple-shows
      security:
        - oauth_2_0: []
      summary: |
        Get Several Shows
      tags:
        - Shows
      x-spotify-docs-console-url: /console/get-several-shows/?ids=5CfCWKI5pZ28U0uOzXkDHe,5as3aKmN2k11yfDDDSrvaZ
      x-spotify-docs-endpoint-name: Get Multiple Shows
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Shows
    x-spotify-docs-display-name: several-shows
  "/shows/{id}":
    get:
      description: |
        Get Spotify catalog information for a single show identified by its
        unique Spotify ID.
      operationId: get-a-show
      security:
        - oauth_2_0:
            - user-read-playback-position
      summary: |
        Get Show
      tags:
        - Shows
      x-spotify-docs-console-url: /console/get-show/?id=38bS44xjbVVZ3No3ByF1dJ
      x-spotify-docs-endpoint-name: Get a Show
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Shows
    x-spotify-docs-display-name: show
  "/shows/{id}/episodes":
    get:
      description: |
        Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.
      operationId: get-a-shows-episodes
      security:
        - oauth_2_0:
            - user-read-playback-position
      summary: |
        Get Show Episodes
      tags:
        - Shows
        - Episodes
      x-spotify-docs-console-url: /console/get-show-episodes/
      x-spotify-docs-endpoint-name: Get a Show's Episodes
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Shows
    x-spotify-docs-display-name: show-episodes
  /tracks:
    get:
      description: |
        Get Spotify catalog information for multiple tracks based on their Spotify IDs.
      operationId: get-several-tracks
      security:
        - oauth_2_0: []
      summary: |
        Get Several Tracks
      tags:
        - Tracks
      x-spotify-docs-console-url: /console/get-several-tracks/?ids=3n3Ppam7vgaVa1iaRUc9Lp,3twNvmDtFQtAd5gMKedhLD
      x-spotify-docs-endpoint-name: Get Several Tracks
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Tracks
    x-spotify-docs-display-name: several-tracks
  "/tracks/{id}":
    get:
      description: |
        Get Spotify catalog information for a single track identified by its
        unique Spotify ID.
      operationId: get-track
      security:
        - oauth_2_0: []
      summary: |
        Get Track
      tags:
        - Tracks
      x-spotify-docs-console-url: /console/get-track/?id=3n3Ppam7vgaVa1iaRUc9Lp
      x-spotify-docs-endpoint-name: Get a Track
      x-spotify-policy-list:
        $ref: "#/components/x-spotify-policy/metadataPolicyList"
    x-spotify-docs-category: Tracks
    x-spotify-docs-display-name: track
  "/users/{user_id}":
    get:
      description: |
        Get public profile information about a Spotify user.
      operationId: get-users-profile
      security:
        - oauth_2_0: []
      summary: |
        Get User's Profile
      tags:
        - Users
      x-spotify-docs-console-url: /console/get-users-profile/?user_id=wizzler
      x-spotify-docs-endpoint-name: Get a User's Profile
    x-spotify-docs-category: Users Profile
    x-spotify-docs-display-name: users-profile
  "/users/{user_id}/playlists":
    get:
      description: |
        Get a list of the playlists owned or followed by a Spotify user.
      operationId: get-list-users-playlists
      security:
        - oauth_2_0:
            - playlist-read-private
            - playlist-read-collaborative
      summary: |
        Get User's Playlists
      tags:
        - Playlists
        - Users
      x-spotify-docs-console-url: /console/get-playlists/?user_id=wizzler
      x-spotify-docs-endpoint-name: Get a List of a User's Playlists
    post:
      description: |
        Create a playlist for a Spotify user. (The playlist will be empty until
        you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)
      operationId: create-playlist
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
      summary: |
        Create Playlist
      tags:
        - Playlists
        - Library
      x-spotify-docs-console-url: /console/post-playlists/
      x-spotify-docs-endpoint-name: Create a Playlist
    x-spotify-docs-category: Playlists
    x-spotify-docs-display-name: playlists
components:
  securitySchemes:
    oauth_2_0:
      description: Spotify supports OAuth 2.0 for authenticating all API requests.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          scopes:
            app-remote-control: |
              Communicate with the Spotify app on your device.
            playlist-modify-private: |
              Manage your private playlists.
            playlist-modify-public: |
              Manage your public playlists.
            playlist-read-collaborative: |
              Access your collaborative playlists.
            playlist-read-private: |
              Access your private playlists.
            streaming: |
              Play content and control playback on your other devices.
            ugc-image-upload: |
              Upload images to Spotify on your behalf.
            user-follow-modify: |
              Manage your saved content.
            user-follow-read: |
              Access your followers and who you are following.
            user-library-modify: |
              Manage your saved content.
            user-library-read: |
              Access your saved content.
            user-modify-playback-state: |
              Control playback on your Spotify clients and Spotify Connect devices.
            user-read-currently-playing: |
              Read your currently playing content.
            user-read-email: |
              Get your real email address.
            user-read-playback-position: |
              Read your position in content you have played.
            user-read-playback-state: |
              Read your currently playing content and Spotify Connect devices information.
            user-read-private: |
              Access your subscription details.
            user-read-recently-played: |
              Access your recently played items.
            user-top-read: |
              Read your top artists and content.
          tokenUrl: https://accounts.spotify.com/api/token
      type: oauth2
  x-spotify-policy:
    $ref: ../policies.yaml
    Attribution: {}
    Broadcasting: {}
    CommercialStreaming: {}
    ContentAlteration: {}
    Downloading: {}
    MultipleIntegrations: {}
    StandalonePreview: {}
    Synchronization: {}
    VisualAlteration: {}
    metadataPolicyList:
      - $ref: "#/components/x-spotify-policy/Downloading"
      - $ref: "#/components/x-spotify-policy/VisualAlteration"
      - $ref: "#/components/x-spotify-policy/Attribution"
    playerPolicyList:
      - $ref: "#/components/x-spotify-policy/CommercialStreaming"
      - $ref: "#/components/x-spotify-policy/ContentAlteration"
      - $ref: "#/components/x-spotify-policy/Synchronization"
      - $ref: "#/components/x-spotify-policy/Broadcasting"
