from langchain_integrations.embeddings.huggingface import HuggingFaceEmbeddings
from langchain_integrations.embeddings.huggingface import HuggingFaceInstructEmbeddings
from langchain_integrations.embeddings.huggingface import HuggingFaceBgeEmbeddings
from langchain_integrations.embeddings.huggingface import HuggingFaceInferenceAPIEmbeddings
__all__ = ['HuggingFaceEmbeddings', 'HuggingFaceInstructEmbeddings', 'HuggingFaceBgeEmbeddings', 'HuggingFaceInferenceAPIEmbeddings']