from langchain_integrations.document_loaders.word_document import Docx2txtLoader
from langchain_integrations.document_loaders.word_document import UnstructuredWordDocumentLoader
__all__ = ['Docx2txtLoader', 'UnstructuredWordDocumentLoader']